name = "ACE-grenades-in-hatches"
prefix = "grenades_hatches"
author = "johnb43"
template = "cba"
mainprefix = "x"
files = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "README.md"
]
folder_optionals = false
sig_version = 3
